apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: meta
  name: deployment-reader
rules:
- apiGroups: ["apps"] # "" indicates the core API group
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]
